services:
  mind:
    build:
      context: ./app
    container_name: aidna-mind
    environment:
      - ENVIRONMENT_URL=http://aidna-api:8000
      - BODY_URL=http://aidna-body:8000
      - POLL_INTERVAL=1.0
      - LOOP_DELAY=0.1
    volumes:
      - ./app:/app
    restart: unless-stopped

networks:
  default:
    name: aidna-network
    external: true
